name: Build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  verify:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [msvc, clang-cl]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: '3.1.1'

      - name: Configure
        shell: pwsh
        run: xmake f -y -m releasedbg --toolchain=${{ matrix.toolchain }} --deploy_dir=

      - name: Verify
        run: xmake verify
